services:
  app:
    build:
      args:
        APP_ENV: development
    volumes:
      - .:/var/www
    environment:
      APP_DEBUG: true
      APP_ENV: development
      APP_SUPERVISOR_USER: "root"
      LOG_LEVEL: debug

  nginx:
    volumes:
      - ./public:/var/www/public:ro
